### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, -2, 4], [2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6, 2]])
print(a+b)
print(a-b)

[[6 0 7]
 [6 6 1]]
[[-4 -4  1]
 [-2 -6 -3]]


2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [ ]:
a = np.array([[1, 2], [2, -1], [3, 0]])
b = np.array([[-1, 1], [1, 2], [0, 0]])
c =  a - b*3
print(c)

[[ 4 -1]
 [-1 -7]
 [ 3  0]]


3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [ ]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])
c =  a@b
print(c)

[[-1  1]
 [ 2  2]
 [ 3  3]]


4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [ ]:
a = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [ ]:
a = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
a_inv = np.linalg.inv(a)
a_inv_inv = np.linalg.inv(a_inv)
print(a_inv)
print(a_inv_inv)

[[ 0.07407407  0.14814815  0.18518519]
 [ 0.2037037  -0.09259259 -0.24074074]
 [-0.16666667  0.16666667 -0.16666667]]
[[ 3.  3. -1.]
 [ 4.  1.  3.]
 [ 1. -2. -2.]]
